### ISSUE TITLE
How to implement custom routes?

### ISSUE THREAD

**Issue by jedfoster** [pharindoko/json-serverless#434]
I'm trying to figure out how to implement custom routes using [json-server's rewriter](https://github.com/typicode/json-server#rewriter-example).

I have tried this:

```typescript
server.use(jsonServer.rewriter({
  '/blog/:resource/:id/show': '/:resource/:id',
  '/articles?id=:id': '/posts/:id'
}))

let core: CoreApp | undefined;
```

But I get `404 Not Found` from http://localhost:3000/dev/api/blog/posts/1/show (I'm using the example JSON from the [json-server readme](https://github.com/typicode/json-server#getting-started)) http://localhost:3000/dev/api/posts/1 works just fine.

What am I doing wrong?

---

On a related note, it would be nice if [the `api/` path](https://github.com/pharindoko/json-serverless/blob/master/packages/server/src/app/core.app.ts#L104) could be configured from appconfig.json. I may put in a PR for that change.

**Comment by pharindoko** [comment]
Hey @jedfoster,

I didn‘t try out the custom routes. But now I‘m interested to see why it doesn‘t work.

PRs are always welcome. there‘s room for improvements. 👍

**Comment by pharindoko** [comment]
#439

**Comment by pharindoko** [comment]
Hey @jedfoster,

I tested it - your missing the apiRoutePath in this case /api in this mapping 

````
server.use(
  jsonserver.rewriter({
    '/articles?id=:id': '/api/posts/:id',
  })
);
```

**Comment by jedfoster** [comment]
Sure enough. I thought I had tried every possible permutation, but apparently I missed one.

Changed my rewrite rule to: 

```javascript
server.use(
  jsonServer.rewriter({
    '/blog/:resource/:id/show': '/api/:resource/:id',
    '/articles?id=:id': '/api/posts/:id'
  })
);
```

And now http://localhost:3000/dev/blog/posts/1/show works perfectly.

**Comment by scafmac** [comment]
I didn't want to open a new issue, since I expect I'm missing something, but I can't get the rewriter example to work. I also am trying to figure out how exactly to customize the response object as described in [this custom response example](https://github.com/typicode/json-server#custom-output-example) - any chance there's an example of that for json-serverless around?

I tried a few variations on including `api` for the custom routes, but they continued to return a 404. The target paths work fine. Here's my code from `handler.ts`

`
...
const jsonServer = require("json-server");
const server = express();

server.use(
	jsonServer.rewriter({
		"/clientService/client/*": "/api/clientService-client/$1",
		"/clientService/nav/*": "/api/clientService-nav/$1"
	})
);

const sls = serverlessHttp(server);
...
`

Anything obvious stand out to you?

Thanks for json-serverless. I'm excited to use it.

**Comment by pharindoko** [comment]
@scafmac 
this seems to be tricky.
I tried again the rewriter @jedfoster mentioned again **and this worked.**

but I couldn`t even use this rewriter locally

```
server.use(
  jsonServer.rewriter({
    'api/*': '/$1',
  })
);
```

need to test tomorrow if it works with json-server itself....

br,

@pharindoko

**Comment by pharindoko** [comment]
@scafmac sorry but I haven`t found the issue. 
Does this work with json server but not with json-serverless itself ?
Please provide a small example - would be helpful for testing.

br,

@pharindoko

**Comment by pharindoko** [comment]
I will close this issue now as I did not receive a further reply.
Can`t solve this yet.
